version: '3.8'

services:
  db:
    image: "mysql:8.0"
    container_name: is4103-db
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: is4103db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes: 
    - is4103-data:/var/lib/mysql

volumes:
  is4103-data: